Update dockerfile

diff --git a/server/docker/dockerfile b/server/docker/dockerfile
--- a/server/docker/dockerfile
+++ b/server/docker/dockerfile
@@ -1,42 +1,57 @@
 # Basic system
 FROM debian:12-slim
 
-# tinc server argument
-ENV NETWORK_NAME="docker"
-ENV LISTEN_PORT="655"
-ENV PMTU_DISCOVERY="yes"
-ENV IPV4_SUBNET_RANGE_BEGIN="10.77.1.1"
-ENV IPV4_SUBNET_RANGE_END="10.77.255.255"
-ENV IPV4_SUBNET_PREFIX="24"
-ENV IPV4_SUBNET_MASK="255.255.0.0"
+# Put apt related things at very top of dockerfile for cache as much as possible
+# apt proxy if proxy is set in terminal that run docker build
+ENV aptProxyConfig="/etc/apt/apt.conf.d/docker_build"
+RUN touch $aptProxyConfig
+RUN if [ -n "$HTTP_PROXY" ]; then echo "Acquire::http::Proxy \"$HTTP_PROXY\";" >> $aptProxyConfig; fi
+RUN if [ -n "$HTTPS_PROXY" ]; then echo "Acquire::http::Proxy \"$HTTPS_PROXY\";" >> $aptProxyConfig; fi
+# Try limit apt multi thread download connection count in weak network
+RUN echo 'Acquire::Queue-Mode "access";' >> $aptProxyConfig
+# More retry on connection lost, default seems 3
+RUN echo 'Acquire::Retries "300";' >> $aptProxyConfig
+RUN cat $aptProxyConfig
+
+# Install compiler to build tinc
+# Install dnsmasq
+# Install jre 17 for run tinc management tool
+# Install start script tool
+# Install common network tool
+# Run apt update and apt install in same command to prevent cache miss
+RUN apt-get update && apt-get install -y \
+    build-essential libncurses5-dev libreadline6-dev libzlcore-dev zlib1g-dev liblzo2-dev libssl-dev \
+    dnsmasq \
+    openjdk-17-jre \
+    lsof \
+    iproute2 iputils-ping
+
+# Delete apt config used during build
+RUN rm "$aptProxyConfig"
 
 # Copy things to
 WORKDIR /home/root
 
-# apt proxy if proxy is set in terminal that run docker build
-ENV aptProxyConfig="/etc/apt/apt.conf.d/proxy"
-RUN touch $aptProxyConfig
-RUN if [ -n "$HTTP_PROXY" ]; then echo "Acquire::http::Proxy \"$HTTP_PROXY\";" >> $aptProxyConfig; fi
-RUN if [ -n "$HTTPS_PROXY" ]; then echo "Acquire::http::Proxy \"$HTTPS_PROXY\";" >> $aptProxyConfig; fi
-RUN cat $aptProxyConfig
-
-# Install compiler, run apt update and apt install in same command to prevent cache miss
-RUN apt-get update && apt-get install -y \
-    build-essential \
-    libncurses5-dev \
-    libreadline6-dev \
-    libzlcore-dev \
-    zlib1g-dev \
-    liblzo2-dev \
-    libssl-dev
 # Copy tinc source code
 COPY Downloads/tinc-1.1pre18.tar.gz /home/root/
 RUN tar xvf tinc-1.1pre18.tar.gz
 # cd source code dir and build
 WORKDIR tinc-1.1pre18
 RUN ./configure
-RUN make
+RUN make -j6
 RUN make install
+WORKDIR /home/root
+
+# tinc server argument
+ENV NETWORK_NAME="tinc_docker"
+ENV LISTEN_PORT="655"
+ENV PMTU_DISCOVERY="yes"
+ENV IPV4_SERVER_ADDRESS="10.77.1.1"
+ENV IPV4_SUBNET_RANGE_BEGIN="10.77.1.2"
+ENV IPV4_SUBNET_RANGE_END="10.77.255.254"
+ENV IPV4_SUBNET_PREFIX="24"
+ENV IPV4_SUBNET_MASK="255.255.0.0"
+ENV DHCP_EXPIRE="12h"
 
 # Init tinc server
 RUN mkdir -p /usr/local/var/run
@@ -50,13 +65,71 @@ ENV tincUpScript="/usr/local/etc/tinc/$NETWORK_NAME/tinc-up"
 RUN touch $tincUpScript
 RUN echo "#!/bin/sh" > $tincUpScript
 RUN echo "" >> $tincUpScript
-RUN echo "ip addr add $IPV4_SUBNET_RANGE_BEGIN/$IPV4_SUBNET_PREFIX dev \$INTERFACE" >> $tincUpScript
+RUN echo "ip addr add $IPV4_SERVER_ADDRESS/$IPV4_SUBNET_PREFIX dev \$INTERFACE" >> $tincUpScript
 RUN echo "# Necessary to do interface up here otherwise cause Can't write to Linux tun/tap device (tun mode) /dev/net/tun: Input/output error" >> $tincUpScript
-RUN echo "ip link set $INTERFACE up" >> $tincUpScript
-RUN echo "systemctl restart dnsmasq_$NETWORK_NAME" >> $tincUpScript
+RUN echo "ip link set \$INTERFACE up" >> $tincUpScript
+RUN echo "service dnsmasq restart" >> $tincUpScript
 RUN echo "" >> $tincUpScript
 RUN echo "#echo 'Unconfigured tinc-up script, please edit '$0'!'" >> $tincUpScript
 RUN echo "" >> $tincUpScript
 RUN echo "#ifconfig $INTERFACE <your vpn IP address> netmask <netmask of whole VPN>" >> $tincUpScript
 RUN echo "" >> $tincUpScript
 RUN cat $tincUpScript
+
+# DHCP config
+# dnsmasq is started by using tinc-up interface up script
+ENV dnsmasqConfig="/etc/dnsmasq.conf"
+RUN echo "port=0" > $dnsmasqConfig
+RUN echo "interface=$NETWORK_NAME" >> $dnsmasqConfig
+RUN echo "dhcp-range=$IPV4_SUBNET_RANGE_BEGIN,$IPV4_SUBNET_RANGE_END,$IPV4_SUBNET_MASK,$DHCP_EXPIRE" >> $dnsmasqConfig
+RUN echo "dhcp-option=option:router" >> $dnsmasqConfig
+RUN echo "dhcp-option=option:dns-server" >> $dnsmasqConfig
+RUN echo "" >> $dnsmasqConfig
+RUN cat $dnsmasqConfig
+
+# Copy tinc management tool
+COPY Downloads/spring-boot-project-0.0.1-SNAPSHOT.jar /home/root/
+
+# Make start script
+ENV startScript="/home/root/start.sh"
+RUN echo "#!/bin/bash" > $startScript
+RUN echo "" >> $startScript
+RUN echo "cleanup() {" >> $startScript
+# Send Ctrl+C to process has port 8080
+RUN echo "    tincPid=\$(lsof -t -i:\$LISTEN_PORT)" >> $startScript
+RUN echo "    springBootPid=\$(lsof -t -i:8080)" >> $startScript
+RUN echo "    kill -15 \$springBootPid" >> $startScript
+RUN echo "    wait \$springBootPid" >> $startScript
+RUN echo "    tinc -n $NETWORK_NAME stop" >> $startScript
+RUN echo "    tail --pid=\$tincPid -f /dev/null" >> $startScript
+RUN echo '    echo "Safe shutdown"' >> $startScript
+RUN echo "}" >> $startScript
+RUN echo "" >> $startScript
+RUN echo "trap 'cleanup' SIGTERM" >> $startScript
+RUN echo "" >> $startScript
+# Start tinc require at run time instead of build time
+RUN echo "tinc -n $NETWORK_NAME start" >> $startScript
+# Start tinc management tool
+RUN echo "java -jar spring-boot-project-0.0.1-SNAPSHOT.jar &" >> $startScript
+RUN echo "" >> $startScript
+RUN echo "wait \$!" >> $startScript
+RUN echo "" >> $startScript
+RUN chmod +x "$startScript"
+RUN cat $startScript
+
+# Make diagnostic script
+ENV diagScript="/home/root/diagnostic.sh"
+RUN echo "#!/bin/bash" > $diagScript
+RUN echo "" >> $diagScript
+RUN echo 'echo "tincUpScript:"' >> $diagScript
+RUN echo "cat \"$tincUpScript\"" >> $diagScript
+RUN echo "" >> $diagScript
+RUN echo 'echo "dnsmasqConfig:"' >> $diagScript
+RUN echo "cat \"$dnsmasqConfig\"" >> $diagScript
+RUN echo "" >> $diagScript
+RUN echo 'echo "startScript:"' >> $diagScript
+RUN echo "cat \"$startScript\"" >> $diagScript
+RUN echo "" >> $diagScript
+RUN chmod +x "$diagScript"
+
+CMD ["/home/root/start.sh"]
